#!/bin/sh
DIR=$( cd "$( dirname "$0" )" && pwd )
PORT=`cat $DIR/ENV | grep RCON_PORT | awk '{print $3}'`
PASS=`cat $DIR/ENV | grep RCON_PASS | awk '{print $3}'`
#if [ -f $DIR/.TMP/SENDING ] ; then
#	echo Error Error Error Error Error Error Error Error Error Error Error Error Error 
#	exit
#fi
#touch $DIR/.TMP/SENDING
#读取所有参数
for ONE in $*
do
	if [ "$STR" = "" ] ; then
		STR=$ONE
		continue
	fi
	STR=$STR" "$ONE
done
$DIR/Dependencies/py3 $DIR/Dependencies/sendcommand/sendcommand.py $PORT $PASS "$STR"
#echo $STR > $DIR/Dependencies/sendcommand/input.txt
#inotifywait -qq $DIR/Dependencies/sendcommand/output.txt
#head -1 $DIR/Dependencies/sendcommand/output.txt
#rm -f $DIR/.TMP/SENDING
