#!/bin/sh
DIR=$( cd "$( dirname "$0" )" && pwd )
CQ_HOST=`cat $DIR/ENV | grep CQ_HOST | awk '{print $3}'`
QQ_GROUP=`cat $DIR/ENV | grep QQ_GROUP | awk '{print $3}'`
for ONE in $*
do
RAWSTR=$RAWSTR" "$ONE
done
#RAWSTR=`echo $RAWSTR | sed 's/^[ \t]*//g' | tr -d '\n' | xxd -plain | sed 's/\(..\)/%\1/g'`
#RAWSTR=`echo $RAWSTR | sed s/[[:space:]]//g`
curl -s "$CQ_HOST/send_group_msg" --data-urlencode "group_id=$QQ_GROUP" --data-urlencode "message=$RAWSTR" >> /dev/null
