#!/bin/sh
DIR=$( cd "$( dirname "$0" )" && pwd )
SCREEN_NAME=`cat $DIR/ENV | grep SCREEN_NAME | awk '{print $3}'`
SCREEN_NAMELOC=$SCREEN_NAME"LOC"
if [ "$1" == "all" ] ; then
	sh $DIR/list | awk '{ for(i=1; i<=9; i++){ $i="" }; print $0 }' | sed s'/,//g' | xargs -n1 > $DIR/.TMP/list.log
	screen -dmSU $SCREEN_NAMELOC $DIR/Dependencies/sendcommand/startlocation.sh 
	sleep 0.5
	cat $DIR/.TMP/list.log | while read NAME
	do	
		sleep 0.1
		POS=`$DIR/Dependencies/sendcommand/location/send.sh "data get entity $NAME Pos" | awk '{print $(NF-2),$(NF-1),$(NF)}' | sed s'/,//g' | sed s'/d//g' | sed s'/\[//g' | sed s'/\]//g' | awk 'BEGIN{OFS="\n"}{print $1,$2,$3}' | sed "s/\..*//g" | awk '{printf " %s",$1}'`
		sleep 0.1
		DIM=`$DIR/Dependencies/sendcommand/location/send.sh "data get entity $NAME Dimension" | awk '{print $NF}'`
		if [ "$DIM" = "1" ] ; then
			echo $NAME "在 末地 的" $POS
		elif [ "$DIM" = "0" ] ; then
			echo $NAME "在 主世界 的" $POS
		elif [ "$DIM" = "-1" ] ; then
			echo $NAME "在 地狱 的" $POS
		fi
	done
	screen -X -S $SCREEN_NAMELOC quit
else
	NAME="$1"
	POS=`$DIR/send "data get entity $NAME Pos" | awk '{print $(NF-2),$(NF-1),$(NF)}' | sed s'/,//g' | sed s'/d//g' | sed s'/\[//g' | sed s'/\]//g' | awk 'BEGIN{OFS="\n"}{print $1,$2,$3}' | sed "s/\..*//g" | awk '{printf " %s",$1}'`
	DIM=`$DIR/send "data get entity $NAME Dimension" | awk '{print $NF}'`
	if [ "$DIM" = "1" ] ; then
		echo $NAME "在 末地 的" $POS
	elif [ "$DIM" = "0" ] ; then
		echo $NAME "在 主世界 的" $POS
	elif [ "$DIM" = "-1" ] ; then
		echo $NAME "在 地狱 的" $POS
	fi
fi
